#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Felipe Martins do Nascimento — Currículo
url: 'https://resume.wild.dev.br'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: Currículo Digital — Felipe Martins do Nascimento · Infrastructure Analyst · DevOps · Cloud

# Style — dark | blue | turquoise | green | berry | orange | ceramic | teal | oceanstale
theme_skin: dark

chrome_mobile_color: '#0A0E17'

# Tracker
analytics: G-6NT22X2P14

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
